### ISSUE TITLE
中文能生成行图像吗？

### ISSUE THREAD

**Issue by dlml** [dailenson/SDT#10]

**Comment by dailenson** [comment]
感谢您的关注！我们这个工作目前解决的是单字生成问题，暂时还无法支持文本行图像生成，需要将单字拼接成文本行。
文本行生成也是未来我们希望解决的问题~

**Comment by dlml** [comment]
生成的单字图像锯齿感很明显。

**Comment by dailenson** [comment]
我们生成的文字是在线的矢量轨迹，如果想要更清晰的锯齿感弱的文字图像，只需调整渲染函数的分辨率即可：

coords_render(preds[i], split=True, ``width=48, height=48``, thickness=1, board=0)
