### ISSUE TITLE
补充材料在哪里？

### ISSUE THREAD

**Issue by Johnson-yue** [dailenson/SDT#13]
看到论文，效果很棒，感谢作者分享，想训练自己的数据发现有一些资料是在补充材料里，可以给一个补充材料的下载链接嘛？

**Comment by dailenson** [comment]
感谢您的关注~[页面](https://openaccess.thecvf.com/content/CVPR2023/html/Dai_Disentangling_Writer_and_Character_Styles_for_Handwriting_Generation_CVPR_2023_paper.html)底部含有文章的正文、补充材料和arxiv版本

**Comment by lihongteng** [comment]
> 看到论文，效果很棒，感谢作者分享，想训练自己的数据发现有一些资料是在补充材料里，可以给一个补充材料的下载链接嘛？

兄弟，我们能够有个联系方式吗
