### ISSUE TITLE
Missing requirement -- ModuleNotFoundError: No module named 'lmdb'

### ISSUE THREAD

**Issue by staghado** [dailenson/SDT#19]
ModuleNotFoundError: No module named 'lmdb'

**Comment by microboym** [comment]
Hi there,
@staghado are you using a condo environment on your machine? I've got the same error as yours after I've installed `lmdb` with conda. But later I tried to install the package from `condo-forge`, which works. 

You can simply run
```bash
conda remove lmdb
conda install -c conda-forge python-lmdb
```

https://anaconda.org/conda-forge/python-lmdb

**Comment by staghado** [comment]
Hi, 

It works with pip too inside conda
