### ISSUE TITLE
预处理 自己的图片

### ISSUE THREAD

**Issue by SanKiSun** [dailenson/SDT#21]
怎么制作自己的测试数据，data.mdb里面的coordinates是怎么得到的呢

**Comment by dailenson** [comment]
你好~关于如何制作自己的数据，详细步骤可以看两个置顶的issue。这里需要强调的是，在测试过程中，只需要向模型中输入字符图像，不需要coordinates。

**Comment by SanKiSun** [comment]
> 你好~关于如何制作自己的数据，详细步骤可以看两个置顶的issue。这里需要强调的是，在测试过程中，只需要向模型中输入字符图像，不需要coordinates。

谢谢，我在测试生僻字生成的时候发现生成图片和对应的生僻字差别很大，看不出来是该生僻字，我打算重新制作训练用的生僻字数据，这个该怎么处理呢？现在的困惑就是不太清楚data.mdb里面的数据是怎么处理

**Comment by dailenson** [comment]
> > 你好~关于如何制作自己的数据，详细步骤可以看两个置顶的issue。这里需要强调的是，在测试过程中，只需要向模型中输入字符图像，不需要coordinates。
> 
> 谢谢，我在测试生僻字生成的时候发现生成图片和对应的生僻字差别很大，看不出来是该生僻字，我打算重新制作训练用的生僻字数据，这个该怎么处理呢？现在的困惑就是不太清楚data.mdb里面的数据是怎么处理

如果想要重新训练自己的数据，需要有能够采集数据轨迹的设备（例如平板电脑）,轨迹点的格式在论文和补充材料有详细的解释。大致来说，一个字由若干轨迹点组成，每个点的格式为一个五元组(x, y, state_1, state_2, state_3)，x和y分别代表轨迹点的坐标，state_1, state_2, state_3代表pen down，pen up， pen end三种笔画状态。

**Comment by SanKiSun** [comment]
> > > 你好~关于如何制作自己的数据，详细步骤可以看两个置顶的issue。这里需要强调的是，在测试过程中，只需要向模型中输入字符图像，不需要coordinates。
> > 
> > 
> > 谢谢，我在测试生僻字生成的时候发现生成图片和对应的生僻字差别很大，看不出来是该生僻字，我打算重新制作训练用的生僻字数据，这个该怎么处理呢？现在的困惑就是不太清楚data.mdb里面的数据是怎么处理
> 
> 如果想要重新训练自己的数据，需要有能够采集数据轨迹的设备（例如平板电脑）,轨迹点的格式在论文和补充材料有详细的解释。大致来说，一个字由若干轨迹点组成，每个点的格式为一个五元组(x, y, state_1, state_2, state_3)，x和y分别代表轨迹点的坐标，state_1, state_2, state_3代表pen down，pen up， pen end三种笔画状态。

感谢，我找到提供的中文数据集的源了，已经了解过了
