### ISSUE TITLE
加载预训练模型失败 

### ISSUE THREAD

**Issue by xiaero** [dailenson/SDT#26]
加载预训练模型的失败
每次到 46/3510 就会停止
我的环境
Python 3.8
cuda 1.8 
pytorch 2.0.1
easydict 1.9 
einops 0.7.0
![5aff604fb568efc02b7a2f72148867d](https://github.com/dailenson/SDT/assets/42793568/e5b94b5a-8a79-4f19-93cb-6986d86ec86a)
![0c45220f201531e17a5a016880f82f9](https://github.com/dailenson/SDT/assets/42793568/5722f693-a9f6-40a4-8c2b-2f0e622b630a)

**Comment by dailenson** [comment]
把``--sample_size 50``换成``--sample_size all``就好啦

**Comment by xiaero** [comment]
谢谢 ,刚看了一下 代码 看到了 因为那取整计算那块 让我一直以为50个失败了 一直卡46就停止了
