### ISSUE TITLE
程式碼問題回報

### ISSUE THREAD

**Issue by leeyu891222** [dailenson/SDT#28]
我注意到loader.py程式碼中對於中文以外的數據集，有對超過150 points的資料進行過濾。
但ScriptDataset.self.indexes並沒有在__getitem__()中被使用到，導致於英日資料集上只會採用前len(self.indexes)筆資料。

**Comment by dailenson** [comment]
self.indexes表示数据集的长度，并不是用在``__getitem__()``中，而是用在``__len__()``中
