### ISSUE TITLE
fine-tune训练集大小

### ISSUE THREAD

**Issue by CyberAI-XDU** [dailenson/SDT#41]
作者你好，感谢你的工作，我对其非常感兴趣。我现在想利用该工作训练自己的一套字体，想请问一下我上传多少张自己的图片进行训练比较好？是否有实验证明，谢谢。

**Comment by dailenson** [comment]
感谢对我们工作的关注～使用15张自己的手写字符图像即可。最近我会上传一个详细的教程来讲解如何生成自己的手写字体。

**Comment by Neboer** [comment]
感谢作者的热心，非常期待作者能尽快公开生成自定义字体的教程，只要有明确的流程就行。您的项目对我而言意义很大，再次感谢您的研究。

**Comment by dailenson** [comment]
> 感谢作者的热心，非常期待作者能尽快公开生成自定义字体的教程，只要有明确的流程就行。您的项目对我而言意义很大，再次感谢您的研究。

哈喽，教程已经写好啦，见置顶教程，欢迎使用～
