### ISSUE TITLE
文件明明就在指定路径，就是找不到

### ISSUE THREAD

**Issue by maygyd** [dailenson/SDT#51]
![image](https://github.com/dailenson/SDT/assets/142813779/4bfa575d-6cf7-4248-aaee-d0b00d979af4)
![image](https://github.com/dailenson/SDT/assets/142813779/fa834522-645c-4593-9e32-ea06610cef67)
指令及报错：
C:\Windows\system32>python E:\ai\SDT-master\SDT-master\user_generate.py --pretrained_model checkpoint_path --style_path sampal
Traceback (most recent call last):
  File "E:\ai\SDT-master\SDT-master\user_generate.py", line 78, in <module>
    main(opt)
  File "E:\ai\SDT-master\SDT-master\user_generate.py", line 14, in main
    cfg_from_file(opt.cfg_file)
  File "E:\ai\SDT-master\SDT-master\parse_config.py", line 214, in merge_cfg_from_file
    with open(cfg_filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/CHINESE_USER.yml'

**Comment by chengtx809** [comment]
我也遇到这个问题，是通过--cfg指定绝对路径搞好的，如我的是在给的启动参数后面加上：
--cfg D:\HuaweiMoveData\Users\mianl\Desktop\SDT-master\configs\CHINESE_USER.yml

**Comment by maygyd** [comment]
[自动回复]Sorry,the DALAO you talked with is so busy that can't answer you forever,please never send amessages again.

**Comment by maygyd** [comment]
是直接改文件的代码吗

**Comment by maygyd** [comment]
> 我也遇到这个问题，是通过--cfg指定绝对路径搞好的，如我的是在给的启动参数后面加上： --cfg D:\HuaweiMoveData\Users\mianl\Desktop\SDT-master\configs\CHINESE_USER.yml

![image](https://github.com/dailenson/SDT/assets/142813779/e8f6bbcf-ba5d-4ce5-9836-f48b7c8c41ce)
还是不行

**Comment by chengtx809** [comment]
那我也不清楚了：（
蹲下原作者大佬

**Comment by chengtx809** [comment]
那我也不清楚了：（
蹲下原作者大佬

**Comment by 13232308597** [comment]
> ![image](https://private-user-images.githubusercontent.com/142813779/298060760-4bfa575d-6cf7-4248-aaee-d0b00d979af4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Nzk4MTcsIm5iZiI6MTcwNTY3OTUxNywicGF0aCI6Ii8xNDI4MTM3NzkvMjk4MDYwNzYwLTRiZmE1NzVkLTZjZjctNDI0OC1hYWVlLWQwYjAwZDk3OWFmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjViYzZjNTAzNzAwNzE5MGRkMDViYTdhNWY2YzBlNmVmMjZkNjkyYzE5YzU0ZjllY2U2ZDYzOTQxZGI1NTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CpCN-fVa4JLhdBnp8T7cvec2AchZGWVUybyv98KACbQ) ![image](https://private-user-images.githubusercontent.com/142813779/298060890-fa834522-645c-4593-9e32-ea06610cef67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Nzk4MTcsIm5iZiI6MTcwNTY3OTUxNywicGF0aCI6Ii8xNDI4MTM3NzkvMjk4MDYwODkwLWZhODM0NTIyLTY0NWMtNDU5My05ZTMyLWVhMDY2MTBjZWY2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2M3MzhhMWM5MTVmOGFhZDdkYzEzZTdjM2E4YTAxMjk3YWVmNzU5MjYzYjc3NWIyODc2OGU2MDgwMjRmZGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._8AQKSgSih536Hd15S6XhMObtbdPgjU0bzJ0o6KvuG0) 指令及报错： C:\Windows\system32>python E:\ai\SDT-master\SDT-master\user_generate.py --pretrained_model checkpoint_path --style_path sampal Traceback (most recent call last): File "E:\ai\SDT-master\SDT-master\user_generate.py", line 78, in main(opt) File "E:\ai\SDT-master\SDT-master\user_generate.py", line 14, in main cfg_from_file(opt.cfg_file) File "E:\ai\SDT-master\SDT-master\parse_config.py", line 214, in merge_cfg_from_file with open(cfg_filename, 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'configs/CHINESE_USER.yml'

有两种解决方法，第一种是直接在指令行命令输入“cd E:\ai\SDT-master\SDT-master”
第二种是直接在对应文件夹路径框里输入“cmd”，回车。
完事后当前工作目录就会改变，由原来的C:\Windows\system32>变成E:\ai\SDT-master\SDT-master>
你学废了吗：）

**Comment by 13232308597** [comment]
这类问题是因为文件不在当前工作目录导致的。当前工作目录在C盘，而文件在E盘，执行程序时在C盘检索不到文件，显示notfound

**Comment by maygyd** [comment]
> > ![image](https://private-user-images.githubusercontent.com/142813779/298060760-4bfa575d-6cf7-4248-aaee-d0b00d979af4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Nzk4MTcsIm5iZiI6MTcwNTY3OTUxNywicGF0aCI6Ii8xNDI4MTM3NzkvMjk4MDYwNzYwLTRiZmE1NzVkLTZjZjctNDI0OC1hYWVlLWQwYjAwZDk3OWFmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjViYzZjNTAzNzAwNzE5MGRkMDViYTdhNWY2YzBlNmVmMjZkNjkyYzE5YzU0ZjllY2U2ZDYzOTQxZGI1NTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CpCN-fVa4JLhdBnp8T7cvec2AchZGWVUybyv98KACbQ) ![image](https://private-user-images.githubusercontent.com/142813779/298060890-fa834522-645c-4593-9e32-ea06610cef67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Nzk4MTcsIm5iZiI6MTcwNTY3OTUxNywicGF0aCI6Ii8xNDI4MTM3NzkvMjk4MDYwODkwLWZhODM0NTIyLTY0NWMtNDU5My05ZTMyLWVhMDY2MTBjZWY2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTUxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2M3MzhhMWM5MTVmOGFhZDdkYzEzZTdjM2E4YTAxMjk3YWVmNzU5MjYzYjc3NWIyODc2OGU2MDgwMjRmZGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._8AQKSgSih536Hd15S6XhMObtbdPgjU0bzJ0o6KvuG0) 指令及报错： C:\Windows\system32>python E:\ai\SDT-master\SDT-master\user_generate.py --pretrained_model checkpoint_path --style_path sampal Traceback (most recent call last): File "E:\ai\SDT-master\SDT-master\user_generate.py", line 78, in main(opt) File "E:\ai\SDT-master\SDT-master\user_generate.py", line 14, in main cfg_from_file(opt.cfg_file) File "E:\ai\SDT-master\SDT-master\parse_config.py", line 214, in merge_cfg_from_file with open(cfg_filename, 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'configs/CHINESE_USER.yml'
> 
> 有两种解决方法，第一种是直接在指令行命令输入“cd E:\ai\SDT-master\SDT-master” 第二种是直接在对应文件夹路径框里输入“cmd”，回车。 完事后当前工作目录就会改变，由原来的C:\Windows\system32>变成E:\ai\SDT-master\SDT-master> 你学废了吗：）

这一步解决了，谢谢

**Comment by dailenson** [comment]
一个最粗暴的方法就是把有问题的路径都改成绝对路径
