### ISSUE TITLE
请问作者可以再写一个程序生成ttf吗

### ISSUE THREAD

**Issue by CreeperAWA** [dailenson/SDT#63]
网上找了半天没找着合适的png转ttf软件，请问作者能针对本项目做一个生成ttf的程序吗

**Comment by chiaoooo** [comment]
我有做一個png轉ttf專案 https://github.com/chiaoooo/PngToTTF，給你參考看看～

**Comment by chiaoooo** [comment]
https://hackmd.io/@h93YMTP_SrK5XODkOdtuKg/Sk20ATBMp
這是我之前做的說明書，可以先參考，我之後再更新到readme上

**Comment by CreeperAWA** [comment]
> https://hackmd.io/@h93YMTP_SrK5XODkOdtuKg/Sk20ATBMp 這是我之前做的說明書，可以先看看，我之後再更新到 readme 上

等你更新到README上吧，我這裡打不開

**Comment by chiaoooo** [comment]
我更新上去了 👍

**Comment by CreeperAWA** [comment]
> 我更新上去了 👍

谢谢！
