### ISSUE TITLE
怎么查看生成结果

### ISSUE THREAD

**Issue by yi-dian-dou-bu-dong** [dailenson/SDT#74]
这部份内容是生成字的结果吗，怎么查看
![ff1c59e1f5f96f544289f9d2f168a52](https://github.com/dailenson/SDT/assets/164739352/be028dad-25ca-4d1b-8d19-333598256167)

**Comment by dailenson** [comment]
把store_type的值改成img，重新生成一次就好

**Comment by yi-dian-dou-bu-dong** [comment]
![1711465578237](https://github.com/dailenson/SDT/assets/164739352/c30531d5-8fbf-4da8-956d-199fe880e7a3)看到生成文字了，这些图片名前缀数字是代表什么

**Comment by 369-SN** [comment]
test.py generates images that all seem to have the same font. How can I modify the input data to generate other fonts? In addition, is there a specific division and naming for different fonts?

**Comment by dailenson** [comment]
> ![1711465578237](https://private-user-images.githubusercontent.com/164739352/316919158-c30531d5-8fbf-4da8-956d-199fe880e7a3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODM1MTEsIm5iZiI6MTcxMTc4MzIxMSwicGF0aCI6Ii8xNjQ3MzkzNTIvMzE2OTE5MTU4LWMzMDUzMWQ1LThmYmYtNGRhOC05NTZkLTE5OWZlODgwZTdhMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwNzIwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWMzNmE0NTA5ZWE0ODhiMmMwNGVlMDdmZjNjNTVlNGUxZWUyM2M0YjQ5ODkwZTcwZjlhYThiM2U3YmFjNTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E1erBG7kYqL1dBu5PelnHOtVWQ1hRnF45NDES0lW9S0)看到生成文字了，这些图片名前缀数字是代表什么

数字代表测试集书写者的ID

**Comment by dailenson** [comment]
> test.py generates images that all seem to have the same font. How can I modify the input data to generate other fonts? In addition, is there a specific division and naming for different fonts?

You can directly use ``user_generate.py`` to achieve your goal. Specifically, firstly process your style samples, then put them in a specific folder, finally run ``user_generate.py``.
