### ISSUE TITLE
Some questions about the generated results

### ISSUE THREAD

**Issue by jackwolfey** [dailenson/SDT#79]
I have been succesfully execute your code by using your well trained model in the readme, but the chinese generated results seems always be one particular character style.I use windows paint to write 15 chars, and make a image binaryzation before inference and still have this problem.Is there any way to fix this issue or any way to imporve the generated results? Nice work by the way.

**Comment by dailenson** [comment]
Hi, there. You‘d better provide more problem details, such as your style samples, your generated results, and which file you execute, ``test.py`` or ``user_generate.py``.

**Comment by jackwolfey** [comment]
Okay, i followed #43 and execute the `user_generate.py`.
Here are my handwriting samples:
![explorer_VCT9kjGItb](https://github.com/dailenson/SDT/assets/91648300/f71bf7bd-b7ea-473a-88d3-43725be67b57)
Here are my generated results:
![explorer_veWceKbvN9](https://github.com/dailenson/SDT/assets/91648300/3933b167-b768-4071-9b3b-46d12558807c)

**Comment by dailenson** [comment]
Based on your generated results, we recommend changing the style sample collection approach to enhance performance, as done in [https://github.com/dailenson/SDT/issues/78#issue-2247810028](url) or [https://github.com/dailenson/SDT/issues/78#issuecomment-2106088105](url) .
