### ISSUE TITLE
不管怎么做都是草书,崩溃了

### ISSUE THREAD

**Issue by aceliuchanghong** [dailenson/SDT#80]
这个是手写不行直接用打字打出来的字体
![image](https://github.com/dailenson/SDT/assets/30772505/52c1142f-f89c-4da1-8370-e78a22776f8e)
,结果还是,这个一,每次都是这个角度,从来没变过..
![image](https://github.com/dailenson/SDT/assets/30772505/8980a0f6-c27f-4b10-9fd0-17d95cfc00b1)
求帮助,或者求style_samples的压缩包

**Comment by dailenson** [comment]
你好，直接用打印字体肯定是不行的，因为我们这个是用于手写体临摹的。手写不行的原因可以对照着置顶issues排查一下～

**Comment by chengtx809** [comment]
可以看下我的这个教程 #56 是使用cpu进行运算的教程（大致参考下
我使用Windows自带的画图，默认画笔，画布300*300成功复现了一个比较理想的效果

**Comment by chengtx809** [comment]
还有一个大佬的可以参考下： #78

**Comment by aceliuchanghong** [comment]
> 可以看下我的这个教程 #56 是使用cpu进行运算的教程（大致参考下 我使用Windows自带的画图，默认画笔，画布300*300成功复现了一个比较理想的效果

谢谢你,大佬,我看看

**Comment by aceliuchanghong** [comment]
把输入的字体调细,效果会好一点,但是还是达不到readme里面的样子
