### ISSUE TITLE
咨询如何生成书写笔画和轨迹坐标的数据？

### ISSUE THREAD

**Issue by wanglifei001** [dailenson/SDT#82]
你好，想咨询如何能够生成书写笔画和轨迹序列坐标， 我想实现手写笔迹的还原，就像项目主页的图片那样[https://raw.githubusercontent.com/dailenson/SDT/master/static/mo_loop.gif](url)
目前自己的训练集已经能够生成比较满意的手写体效果， 想进步不看看能不能获得书写轨迹。
感激不尽~

**Comment by dailenson** [comment]
你好~在``test.py``中将``--store_type``的参数设置成``online``即可输出笔迹的轨迹。

**Comment by wanglifei001** [comment]
好的，已经修改并输出了对应的结果， 非常感谢

**Comment by aceliuchanghong** [comment]
> 好的，已经修改并输出了对应的结果， 非常感谢

这个笔迹如何输出呢?可以给个示范程序吗?
